[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = '/'
healthcheckTimeout = 100
startCommand = "echo 'Launching app 🚀🚀🚀'" # && php artisan key:generate"
